name = "hello-world-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hello-world-db"
database_id = "PLACEHOLDER_DB_ID"
migrations_dir = "migrations"
